# Generated by Django 4.2.11 on 2024-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inference_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="niftiimage",
            name="uploaded_at",
        ),
        migrations.AddField(
            model_name="niftiimage",
            name="desired_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="niftiimage",
            name="mri_mod",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
